---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
activity <- read.csv("activity.csv")

activity$date <- as.POSIXct(activity$date, "%Y-%m-%d")
weekday <- weekdays(activity$date)
activity <- cbind(activity,weekday)

summary(activity)


## What is mean total number of steps taken per day?
png(file="total_number_steps.png", bg="transparent")
hist(activity_total_steps$steps, main = 'Total number of steps taken per day', xlab = 'Total steps taken per day',
     col = 'darkred', ylim = c(0,20), breaks = seq(0,25000, by=2500))
dev.off()
## mean and median number of steps taken per day
mean(activity_total_steps$steps)
##[1] 9354.23
median(activity_total_steps$steps)
##[1] 10395


## What is the average daily activity pattern?
average_daily_activity <- aggregate(activity$steps, by=list(activity$interval), FUN=mean, na.rm=TRUE)
names(average_daily_activity) <- c('interval', 'mean')
png(filename = 'steps per intervals.png',bg = 'transparent')
plot(average_daily_activity$interval, average_daily_activity$mean, type = 'l', col = 'lightblue',
     lwd = 2, main = 'Average number of steps per intervals', xlab = 'Interval', ylab = 'Average number of steps')
dev.off()
## 5-minute interval which contains max steps
average_daily_activity[which.max(average_daily_activity$mean), ]$interval
## [1] 835


## Imputing missing values
imputed_steps <- average_daily_activity$mean[match(activity$interval, average_daily_activity$interval)]
activity_imputed <- transform(activity, steps = ifelse(is.na(activity$steps), yes = imputed_steps, no = activity$steps))
total_steps_imputed <- aggregate(steps ~ date, activity_imputed, sum)
names(total_steps_imputed) <- c("date", "daily_steps")

png(filename = 'total_number_steps_NA.png', bg = 'transparent')
hist(total_steps_imputed$daily_steps, col = "darkgreen", xlab = "Total steps per day", ylim = c(0,30), 
     main = "Total number of steps taken each day", breaks = seq(0,25000,by=2500))
dev.off()
## mean and median
mean(total_steps_imputed$daily_steps)
## [1] 10766.19
median(total_steps_imputed$daily_steps)
## [1] 10766.19

## Are there differences in activity patterns between weekdays and weekends?
activity$date <- as.Date(strptime(activity$date, format="%Y-%m-%d"))
activity$datetype <- sapply(activity$date, function(x) {
        if (weekdays(x) == "Sábado" | weekdays(x) =="Domingo") 
                {y <- "Weekend"} else 
                {y <- "Weekday"}
                y
        })
activity_by_date <- aggregate(steps~interval + datetype, activity, mean, na.rm = TRUE)
png(filename = 'daily_steps_by_type_of_date.png')
plot<- ggplot(activity_by_date, aes(x = interval , y = steps, color = datetype)) +
       geom_line() +
       labs(title = "Average daily steps by type of date", x = "Interval", y = "Average number of steps") +
       facet_wrap(~datetype, ncol = 1, nrow=2)
print(plot)
dev.off()